name: Generate Compressed Hosts File

on:
  push:
    branches: [ "main" ]
  schedule:
    # Run daily at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download host sources
        run: |
          echo "INFO: Downloading from active sources in sources.list..."
          # Filter lines starting with '#' or empty lines, then download
          grep -vE '^\s*(#|$)' lists/sources.list | wget -i - -O hosts.raw
          echo "INFO: Download complete."

      - name: Add custom domains
        run: |
          echo "INFO: Adding custom domains from custom.list..."
          if [ -s lists/custom.list ]; then
            # FIX: Ensure there's a newline before adding custom domains
            echo "" >> hosts.raw
            while IFS= read -r domain; do
              # Ensure line is not empty and not a comment
              if [[ -n "$domain" && ! "$domain" =~ ^\s*# ]]; then
                echo "0.0.0.0 $domain" >> hosts.raw
              fi
            done < lists/custom.list
            echo "INFO: Custom domains added."
          else
            echo "INFO: lists/custom.list is empty. Skipping."
          fi

      - name: Make script executable
        run: chmod +x scripts/hostpress.sh

      - name: Apply whitelist to raw hosts
        run: |
          echo "INFO: Applying whitelist from custom-white.list to hosts.raw..."
          if [ -s lists/custom-white.list ]; then
            # Remove lines containing domains from the whitelist
            # -f option reads patterns from a file, -v inverts the match
            grep -v -f lists/custom-white.list hosts.raw > hosts.raw.whitelisted
            mv hosts.raw.whitelisted hosts.raw
            echo "INFO: Whitelist applied to hosts.raw."
          else
            echo "INFO: lists/custom-white.list is empty. Skipping whitelist application."
          fi

      - name: Run hostpress script to process hosts
        run: |
          echo "INFO: Starting host processing with Bash script..."
          ./scripts/hostpress.sh hosts.raw
          echo "INFO: Host processing finished. Generated multiple output files."

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'Latest - %H:%M (%d %m %Y)')"
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            hosts.txt
            hosts-uncompressed.txt
            dnsmasq.conf
            smartdns.conf
          tag_name: latest
          name: ${{ steps.date.outputs.date }}
          body: |
            Automated hosts file build.
            Triggered by: ${{ github.event_name }}
            Commit: `${{ github.sha }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
